name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@11eadb4c9c20792433e581de2441739952edde4c
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
      - uses: esy/github-action@11eadb4c9c20792433e581de2441739952edde4c
        id: prepare-npm-artifacts
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          prepare-npm-artifacts-mode: true

  bundle:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esy/github-action@11eadb4c9c20792433e581de2441739952edde4c
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          bundle-npm-artifacts-mode: true
