name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: esy/github-action@master
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}




